### ISSUE TITLE
Use GOOD and GOARCH env variables for builds :)

### ISSUE THREAD

**Issue by mghlaiel** [Seifbarouni/go-create#1]
Hola Seif,
I wanted to make a stylish introduction 😁  
I suggest you use `GOOS` and `GOARCH` as input to your build scripts. The env variable can be read as input arguments and you'll only need one build script to target all platforms/architectures instead of two (or more) separate scripts

Find out more [here](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63)

**Comment by seifb01** [comment]
Hey Mounir,
Thank you for this comment I think it's better to have one build file for all platforms. I'll look into it and make the necessary changes. I'll close this issue when I push the new code.
